namespace AliveChessLibrary.Commands
{
    public enum Command : uint
    {
        // команды авторизации:   диапазон: 0 - 5 количество: (6)
        AuthorizeRequest           = 0,
        AuthorizeResponse          = 1,
        ExitFromGameRequest        = 2,
        ExitFromGameResponse       = 3,
        RegisterRequest            = 4,
        RegisterResponse           = 5,

        // команды большой карты: диапазон: 6 - 55 количество: (50)
        BigMapRequest              = 6,
        BigMapResponse             = 7,
        CaptureCastleRequest       = 8,
        CaptureCastleResponse      = 9,
        CaptureMineRequest         = 10,
        CaptureMineResponse        = 11,
        ComeInCastleRequest        = 12,
        ComeInCastleResponse       = 13,
        ContactKingRequest         = 14,
        ContactKingResponse        = 15,
        TakeResourceMessage        = 16,
        //
        MoveKingRequest            = 18,
        MoveKingResponse           = 19,
        ContactCastleRequest       = 20,
        ContactCastleResponse      = 21,
        GetMapRequest              = 22,
        GetMapResponse2D           = 23,
        GetObjectsRequest          = 24,
        GetObjectsResponse         = 25,
        LooseCastleMessage         = 26,
        LooseMineMessage           = 27,
        UpdateWorldMessage         = 28,
        GetResourceMessage         = 29,
        GetMapResponse3D           = 30,

        // команды системного диалога: диапазон: 56 - 75 количество: (20)
        BattleDialogMessage        = 56,
        PayOffDialogMessage        = 57,
        //ProtectDialogMessage       = 58,
        MarketDialogMessage        = 59,
        CapitulateDialogMessage    = 60,
        CaptureCastleDialogMessage = 61,
        DeactivateDialogMessage    = 62,
        CreateUnionDialogMessage   = 63,
        WarDialogMessage           = 64,
        PeaceDialogMessage         = 65,
        JoinEmperiesDialogMessage  = 66,

        // команды замка: диапазон: 76 - 126(50)
        LeaveCastleRequest         = 76,
        LeaveCastleResponse        = 77,
        GetArmyCastleToKingRequest = 78,
        GetArmyCastleToKingResponse = 79,
        GetListBuildingsInCastleRequest  = 80,
        GetListBuildingsInCastleResponse = 81,
        GetRecBuildingsRequest     = 82,
        GetRecBuildingsResponse    = 83,
        ShowArmyCastleRequest      = 84,
        ShowArmyKingRequest        = 85,
        BuildingInCastleRequest    = 86,
        BuildingInCastleResponse   = 87,
        BuyFigureRequest           = 88,
        BuyFigureResponse          = 89,

        // команды шахматного поединка: диапазон 127 - 147(20)
        BattleMessage              = 127,
        DownloadBattlefildRequest  = 128,
        DownloadBattlefildResponse = 129,
        PlayerMoveRequest          = 130,
        PlayerMoveResponse         = 131,
        
        // команды управлениями союзами и империями
        //BuyFigureRequest                = 148,
        JoinRequestMessage              = 149,
        EmbedTaxRateRequest             = 150,
        EmbedTaxRateResponse            = 151,
        ExcludeKingFromEmpireRequest    = 152,
        ExcludeKingFromEmpireResponse   = 153,
        IncludeKingInEmpireRequest      = 154,
        IncludeKingInEmpireResponse     = 155,
        ExitFromAlianceRequest          = 156,
        ExitFromAlianceResponse         = 157,
        GetHelpFigureRequest            = 158,
        GetHelpFigureResponse           = 159,
        GetHelpResourceRequest          = 160,
        GetHelpResourceResponse         = 161,
        GetAlianceInfoRequest           = 162,
        GetAlianceInfoResponse          = 163,
        GrandLeaderPrivilegesMessage    = 164,
        TakeAwayLeaderPrivilegesMessage = 165,
        JoinToAlianceRequest            = 166,
        JoinToAlianceResponse           = 167,
        MessageNewsMessage              = 168,
        SendFigureHelpMessage           = 169,
        SendResourceHelpMessage         = 170,
        StartVoteRequest                = 171,
        StartVoteResponse               = 172,
        StartImpeachmentRequest         = 173,
        StartImpeachmentResponse        = 174,
        VoteBallotMessage               = 175,
        GetAliancesInfoRequest          = 176,
        GetAliancesInfoResponse         = 177,
        ExcludeFromEmpireMessage        = 178,
        StartNegotiateRequest           = 179,
        StartNegotiateResponse          = 180,
        // команды торговли:           ?

        TEST                            = 200
    }
}
