// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.EmpireCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  import MemberInfo;
  public final class AlianceInfo extends Message {
    public function AlianceInfo() {
      registerField("Id","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,2);
      registerField("Name","",Descriptor.STRING,Descriptor.LABEL_OPTIONAL,3);
      registerField("Leader","MemberInfo",Descriptor.MESSAGE,Descriptor.LABEL_OPTIONAL,4);
    }
    // optional int32 _id = 2;
    public var Id:int = 0;
    
    // optional string _name = 3;
    public var Name:String = "";
    
    // optional .AliveChessLibrary.Commands.EmpireCommand.MemberInfo _leader = 4;
    public var Leader:AliveChessLibrary.Commands.EmpireCommand.MemberInfo = null;
    
  
  }
}