// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.EmpireCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class EmbedTaxRateRequest extends Message {
    public function EmbedTaxRateRequest() {
      registerField("Rate","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional int32 _rate = 1;
    public var Rate:int = 0;
    
  
  }
}