// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.EmpireCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class ExcludeKingFromEmpireResponse extends Message {
    public function ExcludeKingFromEmpireResponse() {
      registerField("Successed","",Descriptor.BOOL,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional bool _successed = 1;
    public var Successed:Boolean = false;
    
  
  }
}