// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.EmpireCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class GetAliancesInfoRequest extends Message {
    public function GetAliancesInfoRequest() {
    }
  
  }
}