// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.EmpireCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  import AlianceInfo;
  public final class GetAliancesInfoResponse extends Message {
    public function GetAliancesInfoResponse() {
      registerField("Aliances","AlianceInfo",Descriptor.MESSAGE,Descriptor.LABEL_REPEATED,1);
    }
    // repeated .AliveChessLibrary.Commands.EmpireCommand.AlianceInfo _aliances = 1;
    public var Aliances:Array = new Array();
    
    //fix bug 1 protobuf-actionscript3
    //dummy var using AliveChessLibrary.Commands.EmpireCommand. necessary to avoid following exception
    //ReferenceError: Error #1065: Variable NetworkInfo is not defined.
    //at global/flash.utils::getDefinitionByName()
    //at com.google.protobuf::Message/readFromCodedStream()
    private var AliancesDummy:AliveChessLibrary.Commands.EmpireCommand.AlianceInfo = null;
    
  
  }
}