// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.EmpireCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class GetHelpResourceRequest extends Message {
    public function GetHelpResourceRequest() {
      registerField("ResourceCount","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
      registerField("ResourceType","",Descriptor.ENUM,Descriptor.LABEL_OPTIONAL,2);
    }
    // optional int32 _resourceCount = 1;
    public var ResourceCount:int = 0;
    
    // optional .AliveChessLibrary.Commands.EmpireCommand.ResourceTypes _resourceType = 2;
    public var ResourceType:Number = -1; //No default value for now...
    
  
  }
}