// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.EmpireCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class IncludeKingInEmpireRequest extends Message {
    public function IncludeKingInEmpireRequest() {
      registerField("KingId","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional int32 _kingId = 1;
    public var KingId:int = 0;
    
  
  }
}