// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.EmpireCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class JoinToAlianceRequest extends Message {
    public function JoinToAlianceRequest() {
      registerField("AlianceId","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional int32 _alianceId = 1;
    public var AlianceId:int = 0;
    
  
  }
}