// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.EmpireCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class MemberInfo extends Message {
    public function MemberInfo() {
      registerField("MemberId","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,3);
      registerField("MemberName","",Descriptor.STRING,Descriptor.LABEL_OPTIONAL,4);
    }
    // optional int32 _memberId = 3;
    public var MemberId:int = 0;
    
    // optional string _memberName = 4;
    public var MemberName:String = "";
    
  
  }
}