// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.EmpireCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  import Resource;
  public final class SendResourceHelpMessage extends Message {
    public function SendResourceHelpMessage() {
      registerField("ReceiverId","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
      registerField("Resources","Resource",Descriptor.MESSAGE,Descriptor.LABEL_REPEATED,2);
    }
    // optional int32 _receiverId = 1;
    public var ReceiverId:int = 0;
    
    // repeated .AliveChessLibrary.Commands.EmpireCommand.Resource _resources = 2;
    public var Resources:Array = new Array();
    
    //fix bug 1 protobuf-actionscript3
    //dummy var using AliveChessLibrary.Commands.EmpireCommand. necessary to avoid following exception
    //ReferenceError: Error #1065: Variable NetworkInfo is not defined.
    //at global/flash.utils::getDefinitionByName()
    //at com.google.protobuf::Message/readFromCodedStream()
    private var ResourcesDummy:AliveChessLibrary.Commands.EmpireCommand.Resource = null;
    
  
  }
}