// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.DialogCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class CapitulateDialogMessage extends Message {
    public function CapitulateDialogMessage() {
      registerField("type","",Descriptor.ENUM,Descriptor.LABEL_OPTIONAL,1);
      registerField("disputeId","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,2);
    }
    // optional .AliveChessLibrary.Commands.DialogCommand.DialogState type = 1;
    public var type:Number = -1; //No default value for now...
    
    // optional int32 disputeId = 2;
    public var disputeId:int = 0;
    
  
  }
}