// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.DialogCommand {

  public final class DialogState {
  
    public static var NoState:Number = 0;
    public static var Agree:Number = 1;
    public static var Refuse:Number = 2;
    public static var Offer:Number = 3;
    public static var Coerce:Number = 4;
  
  }
}