// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.DialogCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class PayOffDialogMessage extends Message {
    public function PayOffDialogMessage() {
      registerField("type","",Descriptor.ENUM,Descriptor.LABEL_OPTIONAL,1);
      registerField("disputeId","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,2);
      registerField("resourceType","",Descriptor.ENUM,Descriptor.LABEL_OPTIONAL,3);
      registerField("resourceCount","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,4);
    }
    // optional .AliveChessLibrary.Commands.DialogCommand.DialogState type = 1;
    public var type:Number = -1; //No default value for now...
    
    // optional int32 disputeId = 2;
    public var disputeId:int = 0;
    
    // optional .AliveChessLibrary.Commands.DialogCommand.ResourceTypes resourceType = 3;
    public var resourceType:Number = -1; //No default value for now...
    
    // optional int32 resourceCount = 4;
    public var resourceCount:int = 0;
    
  
  }
}