///////////////////////////////////////////////////////////
//  Animat.cs
//  Implementation of the Class Animat
//  Generated by Enterprise Architect
//  Created on:      16-фев-2009 0:11:06
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using AliveChessLibrary;
using AliveChessLibrary.GameObjects.Abstract;
using AliveChessLibrary.GameObjects.Buildings;
using AliveChessLibrary.GameObjects.Characters;
using AliveChessLibrary.GameObjects.Landscapes;
using AliveChessLibrary.GameObjects.Resources;
using AliveChessLibrary.Interaction;
using AliveChessLibrary.Net;
using AliveChessLibrary.Utility;
using AliveChessServer.LogicLayer.AI.DecisionLayer;
using AliveChessServer.LogicLayer.AI.DecisionLayer.NeuralNetwork;
using AliveChessServer.LogicLayer.AI.PerceptionLayer;

namespace AliveChessServer.LogicLayer.AI
{
    [Table(Name = "dbo.player")]
    public class Animat : IPlayer
    {
        private int _playerId;
        private int _levelId;
        private IList<BotKing> bots;

        private Map _map;
        private VisibleSpace _sector;
        private IMessenger _messenger;

        private bool _isActive;

        private NeuroTeacher _teacher;
        private EntityRef<ILevel> _level;
        private EntitySet<NeuralNetwork> _networks;

        private object _botsSync = new object();

        public Animat()
        {
            this.bots = new List<BotKing>();
            this._level = default(EntityRef<ILevel>);
            this._teacher = new NeuroTeacher();
            this._networks = new EntitySet<NeuralNetwork>();

            NeuralNetwork network = new NeuralNetwork(7, 15, 8);
            network.LearningRate = 0.1;
            this._networks.Add(network);
        }

        public void TeachBots()
        {
            Teacher.Teach(_networks[0]);
            foreach (var botKing in Kings)
                botKing.AttachNeuralNetwork(_networks[0]);
        }

        public void AddBot(BotKing bot)
        {
            lock (_botsSync)
                bots.Add(bot);
        }

        public void RemoveBot(BotKing bot)
        {
            lock (_botsSync)
                bots.Remove(bot);
        }

        public bool HasKing(int kingId)
        {
            return bots.Exists(x => x.Id == kingId);
        }

        public King GetKing()
        {
            if (bots.Count > 0) return bots[0];
            else throw new AliveChessLibrary.AliveChessException("Animat hasn't kings");
        }

        public King GetKing(int kingId)
        {
            return bots.FindElement(x => x.Id == kingId);
        }

        public void AddKing(King king)
        {
            if (king is BotKing)
                AddBot(king as BotKing);
            else throw new AliveChessException("This king is not bot");
        }

        public void RemoveKing(King king)
        {
            if (king is BotKing)
                RemoveBot(king as BotKing);
            else throw new AliveChessException("This king is not bot");
        }

        public void UpdateVisibleSpace(VisibleSpace sector)
        {
            this._sector = sector;
        }

        public void ComeInCastle(King player, MapSector point)
        {
            Castle castle = player.Map.SearchCastleByPointId(point.Id);
            if (castle != null)
                player.ComeInCastle(castle);
        }

        public void ContactCastle(King player, MapSector point)
        {
            //Castle castle = player.Map.SearchCastleByPointId(point.Id);
            //if (castle != null)
            //    player.ComeInCastle(castle);
        }

        public void CollectResource(King player, MapPoint point)
        {
            Resource resource = player.Map.SearchResourceByPointId(point.Id);
            if (resource != null)
            {
                player.Map.RemoveResource(resource);
                player.Resources.Add(resource);
            }
        }

        public bool Ready { get; set; }

        public bool IsSuperUser { get; set; }

        public bool Bot { get { return true; } }

        public IMessenger Messenger
        {
            get { return _messenger; }
            set { _messenger = value; }
        }

        public IList<BotKing> Kings
        {
            get { return this.bots; }
            set { this.bots = value; }
        }

        public NeuroTeacher Teacher
        {
            get { return _teacher; }
        }

        public bool IsActive
        {
            get { return _isActive; }
            set { _isActive = value; }
        }

        public Map Map
        {
            get { return _map; }
            set
            {
                _map = value;
                this._sector = new VisibleSpace(value);
            }
        }

        public VisibleSpace VisibleSpace
        {
            get { return _sector; }
            set { _sector = value; }
        }

        [Column(Name = "animat_id", Storage = "_animatId", CanBeNull = false, DbType = Constants.DB_INT,
          IsPrimaryKey = true, IsDbGenerated = true)]
        public int Id
        {
            get
            {
                return this._playerId;
            }
            set
            {
                if (this._playerId != value)
                {
                    this._playerId = value;
                }
            }
        }

        public ILevel Level
        {
            get
            {
                return this._level.Entity;
            }
            set
            {
                if (_level.Entity != value)
                {
                    if (value != null)
                    {
                        _level.Entity = value;
                    }
                }
            }
        }

        [Column(Name = "level_id", Storage = "_levelId", CanBeNull = false, DbType = Constants.DB_INT)]
        public int LevelId
        {
            get
            {
                return this._levelId;
            }
            set
            {
                if (this._levelId != value)
                {
                    this._levelId = value;
                }
            }
        }

    }//end Animat

}//end namespace BotsLogic