///////////////////////////////////////////////////////////
//  IBrain.cs
//  Implementation of the Interface IBrain
//  Generated by Enterprise Architect
//  Created on:      16-фев-2009 2:10:28
///////////////////////////////////////////////////////////

using AliveChessServer.LogicLayer.AI.DecisionLayer.NeuralNetwork;

namespace AliveChessServer.LogicLayer.AI.DecisionLayer
{
    public interface IBrain
    {
        INeuralNetwork NN { get; set; }
        void Process();
        void Think();
    }//end IBrain

}//end namespace DecisionLayer