// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.RegisterCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class RegisterRequest extends Message {
    public function RegisterRequest() {
      registerField("login","",Descriptor.STRING,Descriptor.LABEL_OPTIONAL,1);
      registerField("password","",Descriptor.STRING,Descriptor.LABEL_OPTIONAL,2);
    }
    // optional string login = 1;
    public var login:String = "";
    
    // optional string password = 2;
    public var password:String = "";
    
  
  }
}