// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.StatisticCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  import WorldDescription;
  public final class GetAvailableMapsResponse extends Message {
    public function GetAvailableMapsResponse() {
      registerField("Worlds","WorldDescription",Descriptor.MESSAGE,Descriptor.LABEL_REPEATED,1);
    }
    // repeated .AliveChessLibrary.Commands.StatisticCommand.WorldDescription _worlds = 1;
    public var Worlds:Array = new Array();
    
    //fix bug 1 protobuf-actionscript3
    //dummy var using AliveChessLibrary.Commands.StatisticCommand. necessary to avoid following exception
    //ReferenceError: Error #1065: Variable NetworkInfo is not defined.
    //at global/flash.utils::getDefinitionByName()
    //at com.google.protobuf::Message/readFromCodedStream()
    private var WorldsDummy:AliveChessLibrary.Commands.StatisticCommand.WorldDescription = null;
    
  
  }
}