// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.StatisticCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class GetAvailableMapsRequest extends Message {
    public function GetAvailableMapsRequest() {
      registerField("WorldType","",Descriptor.ENUM,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional .AliveChessLibrary.Commands.StatisticCommand.WorldType _worldType = 1;
    public var WorldType:Number = -1; //No default value for now...
    
  
  }
}