// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.StatisticCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  import Statistic;
  public final class GetStatisticResponse extends Message {
    public function GetStatisticResponse() {
      registerField("Statistic","Statistic",Descriptor.MESSAGE,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional .AliveChessLibrary.Commands.StatisticCommand.Statistic _statistic = 1;
    public var Statistic:AliveChessLibrary.Commands.StatisticCommand.Statistic = null;
    
  
  }
}