// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.StatisticCommand {

  public final class WorldType {
  
    public static var Local:Number = 0;
    public static var Global:Number = 1;
  
  }
}