// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.StatisticCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class WorldDescription extends Message {
    public function WorldDescription() {
      registerField("MapName","",Descriptor.STRING,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional string _mapName = 1;
    public var MapName:String = "";
    
  
  }
}