// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BattleCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class DownloadBattlefildResponse extends Message {
    public function DownloadBattlefildResponse() {
      registerField("Battle","AliveChessLibrary.Commands.BattleCommand.Battle",Descriptor.MESSAGE,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional .AliveChessLibrary.Commands.BattleCommand.Battle _battle = 1;
    public var Battle:AliveChessLibrary.Commands.BattleCommand.Battle = null;
    
  
  }
}