// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BattleCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class DownloadBattlefieldRequest extends Message {
    public function DownloadBattlefieldRequest() {
      registerField("opponent","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional int32 opponent = 1;
    public var opponent:int = 0;
    
  
  }
}