// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BattleCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class MoveUnitResponse extends Message {
    public function MoveUnitResponse() {
      registerField("Succeess","",Descriptor.BOOL,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional bool _succeess = 1;
    public var Succeess:Boolean = false;
    
  
  }
}