// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.GameObjects.Objects {

  public final class MultyObjectTypes {
  
    public static var Rock:Number = 0;
  
  }
}