// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.GameObjects.Objects{
	
	public final class SingleObjectType	{	
		
			public static var Tree:Number = 0;
			public static var Obstacle:Number = 1;
	}
}