// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.GameObjects.Resources {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class Resource extends Message {
    public function Resource() {
      registerField("ResourceId","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
      registerField("X","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,2);
      registerField("Y","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,3);
      registerField("ResourceType","",Descriptor.ENUM,Descriptor.LABEL_OPTIONAL,4);
      registerField("ResourceCount","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,5);
      registerField("WayCost","",Descriptor.FIXED32,Descriptor.LABEL_OPTIONAL,6);
    }
    // optional int32 _resourceId = 1;
    public var ResourceId:int = 0;
    
    // optional int32 _x = 2;
    public var X:int = 0;
    
    // optional int32 _y = 3;
    public var Y:int = 0;
    
    // optional .AliveChessLibrary.GameObjects.Resources.ResourceTypes _resourceType = 4;
    public var ResourceType:Number = -1; //No default value for now...
    
    // optional int32 _resourceCount = 5;
    public var ResourceCount:int = 0;
    
    // optional fixed32 _wayCost = 6;
    public var WayCost:int = 0;
    
  
  }
}