// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.GameObjects.Landscapes {

  public final class LandscapeTypes {
  
    public static var None:Number = 0;
    public static var Grass:Number = 1;
    public static var Ground:Number = 2;
    public static var Snow:Number = 3;
  
  }
}