// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.GameObjects.Landscapes {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class Map extends Message {
    public function Map() {
      registerField("MapId","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
      registerField("MapSizeX","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,2);
      registerField("MapSizeY","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,3);
      registerField("Name","",Descriptor.STRING,Descriptor.LABEL_OPTIONAL,4);
    }
    // optional int32 _mapId = 1;
    public var MapId:int = 0;
    
    // optional int32 _mapSizeX = 2;
    public var MapSizeX:int = 0;
    
    // optional int32 _mapSizeY = 3;
    public var MapSizeY:int = 0;
    
    // optional string _name = 4;
    public var Name:String = "";
    
  
  }
}