///////////////////////////////////////////////////////////
//  GoalStatuses.cs
//  Implementation of the Class GoalStatuses
//  Generated by Enterprise Architect
//  Created on:      16-фев-2009 0:07:57
///////////////////////////////////////////////////////////

namespace BehaviorAILibrary.BehaviorLayer
{
	public enum GoalStatuses : int 
    {
		Active,
		Completed,
		Inactive,
		Failed
	}//end GoalStatuses

}//end namespace BehaviorLayer