// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.RegisterCommands {

  import com.google.protobuf.*;
  import com.hurlant.math.BigInteger;
  
  import flash.utils.*;
  public final class AuthorizeRequest extends Message {
    public function AuthorizeRequest() {
      registerField("login","",Descriptor.STRING,Descriptor.LABEL_OPTIONAL,1);
      registerField("password","",Descriptor.STRING,Descriptor.LABEL_OPTIONAL,2);
      //registerField("isSuperUser","",Descriptor.BOOL,Descriptor.LABEL_OPTIONAL,3);
    }
    // optional string login = 1;
    public var login:String = "";
    
    // optional string password = 2;
    public var password:String = "";
    
    // optional bool isSuperUser = 3;
    //public var isSuperUser:Boolean = false;
  
  }
}