// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.RegisterCommands {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class AuthorizeResponse extends Message {
    public function AuthorizeResponse() {
      registerField("IsNewPlayer","",Descriptor.BOOL,Descriptor.LABEL_OPTIONAL,1);
      registerField("IsAuthorized","",Descriptor.BOOL,Descriptor.LABEL_OPTIONAL,2);
      registerField("ErrorMessage","",Descriptor.STRING,Descriptor.LABEL_OPTIONAL,3);
    }
    // optional bool _isNewPlayer = 1;
    public var IsNewPlayer:Boolean = false;
    
    // optional bool _isAuthorized = 2;
    public var IsAuthorized:Boolean = false;
    
    // optional string _errorMessage = 3;
    public var ErrorMessage:String = "";
    
  
  }
}