// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.RegisterCommands {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class ExitFromGameRequest extends Message {
    public function ExitFromGameRequest() {
    }
  
  }
}