// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.GameObjects.Buildings {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  import Resource;
  public final class Mine extends Message {
    public function Mine() {
      registerField("MineId","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
      registerField("LeftX","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,2);
      registerField("TopY","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,3);
      registerField("Width","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,4);
      registerField("Height","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,5);
      registerField("WayCost","",Descriptor.FIXED32,Descriptor.LABEL_OPTIONAL,6);
      registerField("GainingResource","Resource",Descriptor.MESSAGE,Descriptor.LABEL_OPTIONAL,7);
      registerField("SizeMine","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,8);
    }
    // optional int32 _mineId = 1;
    public var MineId:int = 0;
    
    // optional int32 _leftX = 2;
    public var LeftX:int = 0;
    
    // optional int32 _topY = 3;
    public var TopY:int = 0;
    
    // optional int32 _width = 4;
    public var Width:int = 0;
    
    // optional int32 _height = 5;
    public var Height:int = 0;
    
    // optional fixed32 _wayCost = 6;
    public var WayCost:int = 0;
    
    // optional .AliveChessLibrary.GameObjects.Buildings.Resource _gainingResource = 7;
    public var GainingResource:AliveChessLibrary.GameObjects.Buildings.Resource = null;
    
    // optional int32 _sizeMine = 8;
    public var SizeMine:int = 0;
    
  
  }
}