// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.GameObjects.Buildings {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class ResBuild extends Message {
    public function ResBuild() {
      registerField("Coal","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
      registerField("Gold","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,2);
      registerField("Iron","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,3);
      registerField("Stone","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,4);
      registerField("Wood","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,5);
    }
    // optional int32 _coal = 1;
    public var Coal:int = 0;
    
    // optional int32 _gold = 2;
    public var Gold:int = 0;
    
    // optional int32 _iron = 3;
    public var Iron:int = 0;
    
    // optional int32 _stone = 4;
    public var Stone:int = 0;
    
    // optional int32 _wood = 5;
    public var Wood:int = 0;
    
  
  }
}