// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.GameObjects.Buildings {

  public final class ResourceTypes {
  
    public static var Coal:Number = 0;
    public static var Gold:Number = 1;
    public static var Iron:Number = 2;
    public static var Stone:Number = 3;
    public static var Wood:Number = 4;
  
  }
}