// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.GameObjects.Abstract {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class FPosition extends Message {
    public function FPosition() {
      registerField("X","",Descriptor.FIXED32,Descriptor.LABEL_OPTIONAL,1);
      registerField("Y","",Descriptor.FIXED32,Descriptor.LABEL_OPTIONAL,2);
    }
    // optional fixed32 _x = 1;
    public var X:int = 0;
    
    // optional fixed32 _y = 2;
    public var Y:int = 0;
    
  
  }
}