// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class BigMapResponse extends Message {
    public function BigMapResponse() {
      registerField("isAllowed","",Descriptor.BOOL,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional bool isAllowed = 1;
    public var isAllowed:Boolean = false;
    
  
  }
}