// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class Border extends Message {
    public function Border() {
      registerField("BorderId","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
      registerField("X","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,2);
      registerField("Y","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,3);
      registerField("WayCost","",Descriptor.FIXED32,Descriptor.LABEL_OPTIONAL,4);
    }
    // optional int32 _borderId = 1;
    public var BorderId:int = 0;
    
    // optional int32 _x = 2;
    public var X:int = 0;
    
    // optional int32 _y = 3;
    public var Y:int = 0;
    
    // optional fixed32 _wayCost = 4;
    public var WayCost:int = 0;
    
  
  }
}