// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  import Mine;
  public final class CaptureMineResponse extends Message {
    public function CaptureMineResponse() {
      registerField("mine","Mine",Descriptor.MESSAGE,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional .AliveChessLibrary.Commands.BigMapCommand.Mine mine = 1;
    public var mine:AliveChessLibrary.Commands.BigMapCommand.Mine = null;
    
  
  }
}