// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import AliveChessLibrary.GameObjects.Buildings.Castle;
  
  import com.google.protobuf.*;
  import com.hurlant.math.BigInteger;
  
  import flash.utils.*;
  
  public final class CaptureCastleResponse extends Message {
    public function CaptureCastleResponse() {
      registerField("castle","AliveChessLibrary.GameObjects.Buildings.Castle",Descriptor.MESSAGE,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional .AliveChessLibrary.Commands.BigMapCommand.Castle castle = 1;
    public var castle: AliveChessLibrary.GameObjects.Buildings.Castle = null;
    
  
  }
}