// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class CaptureMineRequest extends Message {
    public function CaptureMineRequest() {
      registerField("mineId","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional int32 mineId = 1;
    public var mineId:int = 0;
    
  
  }
}