// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class ComeInCastleResponse extends Message {
    public function ComeInCastleResponse() {
      registerField("castleId","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional int32 castleId = 1;
    public var castleId:int = 0;
    
  
  }
}