// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  import FPosition;
  public final class ComputePathResponse extends Message {
    public function ComputePathResponse() {
      registerField("Path","FPosition",Descriptor.MESSAGE,Descriptor.LABEL_REPEATED,1);
    }
    // repeated .AliveChessLibrary.Commands.BigMapCommand.FPosition _path = 1;
    public var Path:Array = new Array();
    
    //fix bug 1 protobuf-actionscript3
    //dummy var using AliveChessLibrary.Commands.BigMapCommand. necessary to avoid following exception
    //ReferenceError: Error #1065: Variable NetworkInfo is not defined.
    //at global/flash.utils::getDefinitionByName()
    //at com.google.protobuf::Message/readFromCodedStream()
    private var PathDummy:AliveChessLibrary.Commands.BigMapCommand.FPosition = null;
    
  
  }
}