// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  import FPosition;
  import FPosition;
  public final class ComputePathRequest extends Message {
    public function ComputePathRequest() {
      registerField("Start","FPosition",Descriptor.MESSAGE,Descriptor.LABEL_OPTIONAL,1);
      registerField("Finish","FPosition",Descriptor.MESSAGE,Descriptor.LABEL_OPTIONAL,2);
    }
    // optional .AliveChessLibrary.Commands.BigMapCommand.FPosition _start = 1;
    public var Start:AliveChessLibrary.Commands.BigMapCommand.FPosition = null;
    
    // optional .AliveChessLibrary.Commands.BigMapCommand.FPosition _finish = 2;
    public var Finish:AliveChessLibrary.Commands.BigMapCommand.FPosition = null;
    
  
  }
}