// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  import Dialog;
  public final class ContactKingResponse extends Message {
    public function ContactKingResponse() {
      registerField("discussion","Dialog",Descriptor.MESSAGE,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional .AliveChessLibrary.Commands.BigMapCommand.Dialog discussion = 1;
    public var discussion:AliveChessLibrary.Commands.BigMapCommand.Dialog = null;
    
  
  }
}