// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  import AliveChessLibrary.Commands.BigMapCommand.King;
  
  public final class Dialog extends Message {
    public function Dialog() {
      registerField("id","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
      registerField("Respondent","AliveChessLibrary.Commands.BigMapCommand.King",Descriptor.MESSAGE,Descriptor.LABEL_OPTIONAL,2);
      registerField("yourStep","",Descriptor.BOOL,Descriptor.LABEL_OPTIONAL,3);
    }
    // optional int32 id = 1;
    public var id:int = 0;
    
    // optional .AliveChessLibrary.Commands.BigMapCommand.King _respondent = 2;
    public var Respondent:AliveChessLibrary.Commands.BigMapCommand.King = null;
    
    // optional bool yourStep = 3;
    public var yourStep:Boolean = false;
    
  
  }
}