// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import AliveChessLibrary.Commands.BigMapCommand.Castle;
  import AliveChessLibrary.Commands.BigMapCommand.King;
  import AliveChessLibrary.GameObjects.Resources.Resource;
  
  import com.google.protobuf.*;
  import com.hurlant.math.BigInteger;
  
  import flash.utils.*;
  public final class GetGameStateResponse extends Message {
    public function GetGameStateResponse() {
      registerField("king","AliveChessLibrary.Commands.BigMapCommand.King",Descriptor.MESSAGE,Descriptor.LABEL_OPTIONAL,1);
      registerField("castle","AliveChessLibrary.Commands.BigMapCommand.Castle",Descriptor.MESSAGE,Descriptor.LABEL_OPTIONAL,2);
      registerField("startResources","AliveChessLibrary.GameObjects.Resources.Resource",Descriptor.MESSAGE,Descriptor.LABEL_REPEATED,3);
    }
    // optional .AliveChessLibrary.Commands.BigMapCommand.King king = 1;
    public var king:AliveChessLibrary.Commands.BigMapCommand.King = null;
    
    // optional .AliveChessLibrary.Commands.BigMapCommand.Castle castle = 2;
    public var castle:AliveChessLibrary.Commands.BigMapCommand.Castle = null;
    
    // repeated .AliveChessLibrary.Commands.BigMapCommand.Resource startResources = 3;
    public var startResources:Array = new Array();
    
    //fix bug 1 protobuf-actionscript3
    //dummy var using AliveChessLibrary.Commands.BigMapCommand. necessary to avoid following exception
    //ReferenceError: Error #1065: Variable NetworkInfo is not defined.
    //at global/flash.utils::getDefinitionByName()
    //at com.google.protobuf::Message/readFromCodedStream()
    private var startResourcesDummy:AliveChessLibrary.GameObjects.Resources.Resource = null;
    
  
  }
}