// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
//  import King;
  public final class GetKingResponse extends Message {
    public function GetKingResponse() {
      registerField("King","AliveChessLibrary.Commands.BigMapCommand.King",Descriptor.MESSAGE,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional .AliveChessLibrary.Commands.BigMapCommand.King _king = 1;
    public var King:AliveChessLibrary.Commands.BigMapCommand.King = null;
    
  
  }
}