// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  import AliveChessLibrary.GameObjects.Objects.*;
  
  public final class GetMapResponse extends Message {
    public function GetMapResponse() {
      registerField("mapId","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
      registerField("sizeMapX","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,2);
      registerField("sizeMapY","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,3);
      registerField("Castles","AliveChessLibrary.Commands.BigMapCommand.Castle",Descriptor.MESSAGE,Descriptor.LABEL_REPEATED,4);
      registerField("Mines","AliveChessLibrary.Commands.BigMapCommand.Mine",Descriptor.MESSAGE,Descriptor.LABEL_REPEATED,5);
      registerField("BasePoints","AliveChessLibrary.Commands.BigMapCommand.BasePoint",Descriptor.MESSAGE,Descriptor.LABEL_REPEATED,6);
       registerField("SingleObjects","AliveChessLibrary.GameObjects.Objects.SingleObject",Descriptor.MESSAGE,Descriptor.LABEL_REPEATED,7);
	  registerField("MultyObjects","AliveChessLibrary.GameObjects.Objects.MultyObject",Descriptor.MESSAGE,Descriptor.LABEL_REPEATED,8);
	  registerField("Borders","AliveChessLibrary.GameObjects.Objects.Border",Descriptor.MESSAGE,Descriptor.LABEL_REPEATED,9);
    }
    // optional int32 mapId = 1;
    public var mapId:int = 0;
    
    // optional int32 sizeMapX = 2;
    public var sizeMapX:int = 0;
    
    // optional int32 sizeMapY = 3;
    public var sizeMapY:int = 0;
    
    // repeated .AliveChessLibrary.Commands.BigMapCommand.Castle _castles = 4;
    public var Castles:Array = new Array();
    
    //fix bug 1 protobuf-actionscript3
    //dummy var using AliveChessLibrary.Commands.BigMapCommand. necessary to avoid following exception
    //ReferenceError: Error #1065: Variable NetworkInfo is not defined.
    //at global/flash.utils::getDefinitionByName()
    //at com.google.protobuf::Message/readFromCodedStream()
    private var CastlesDummy:AliveChessLibrary.Commands.BigMapCommand.Castle = null;
    
    // repeated .AliveChessLibrary.Commands.BigMapCommand.Mine _mines = 5;
    public var Mines:Array = new Array();
    
    //fix bug 1 protobuf-actionscript3
    //dummy var using AliveChessLibrary.Commands.BigMapCommand. necessary to avoid following exception
    //ReferenceError: Error #1065: Variable NetworkInfo is not defined.
    //at global/flash.utils::getDefinitionByName()
    //at com.google.protobuf::Message/readFromCodedStream()
    private var MinesDummy:AliveChessLibrary.Commands.BigMapCommand.Mine = null;
    
    // repeated .AliveChessLibrary.Commands.BigMapCommand.BasePoint _basePoints = 6;
    public var BasePoints:Array = new Array();
    
    //fix bug 1 protobuf-actionscript3
    //dummy var using AliveChessLibrary.Commands.BigMapCommand. necessary to avoid following exception
    //ReferenceError: Error #1065: Variable NetworkInfo is not defined.
    //at global/flash.utils::getDefinitionByName()
    //at com.google.protobuf::Message/readFromCodedStream()
    private var BasePointsDummy:AliveChessLibrary.Commands.BigMapCommand.BasePoint = null;
    
        public var SingleObjects:Array = new Array();
	private var SingleObjectsDummy:AliveChessLibrary.GameObjects.Objects.SingleObject = null;
	
	public var MultyObjects:Array = new Array();
	private var MultyObjectsDummy:AliveChessLibrary.GameObjects.Objects.MultyObject = null;
		
	public var Borders:Array = new Array();
	private var BordersDummy:AliveChessLibrary.GameObjects.Objects.Border = null;
  
  }
}