// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class GetObjectsRequest extends Message {
    public function GetObjectsRequest() {
      registerField("observerId","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
      registerField("forConcreteObserver","",Descriptor.BOOL,Descriptor.LABEL_OPTIONAL,2);
      registerField("observerType","",Descriptor.ENUM,Descriptor.LABEL_OPTIONAL,3);
    }
    // optional int32 observerId = 1;
    public var observerId:int = 0;
    
    // optional bool forConcreteObserver = 2;
    public var forConcreteObserver:Boolean = false;
    
    // optional .AliveChessLibrary.Commands.BigMapCommand.PointTypes observerType = 3;
    public var observerType:Number = -1; //No default value for now...
    
  
  }
}