// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  import AliveChessLibrary.GameObjects.Resources.Resource;
  import AliveChessLibrary.Commands.BigMapCommand.King;
  
  public final class GetObjectsResponse extends Message {
    public function GetObjectsResponse() {
      registerField("Resources","AliveChessLibrary.GameObjects.Resources.Resource",Descriptor.MESSAGE,Descriptor.LABEL_REPEATED,1);
      registerField("Kings","AliveChessLibrary.Commands.BigMapCommand.King",Descriptor.MESSAGE,Descriptor.LABEL_REPEATED,2);
    }
    // repeated .AliveChessLibrary.Commands.BigMapCommand.Resource _resources = 1;
    public var Resources:Array = new Array();
    
    //fix bug 1 protobuf-actionscript3
    //dummy var using AliveChessLibrary.Commands.BigMapCommand. necessary to avoid following exception
    //ReferenceError: Error #1065: Variable NetworkInfo is not defined.
    //at global/flash.utils::getDefinitionByName()
    //at com.google.protobuf::Message/readFromCodedStream()
    private var ResourcesDummy:AliveChessLibrary.GameObjects.Resources.Resource = null;
    
    // repeated .AliveChessLibrary.Commands.BigMapCommand.King _kings = 2;
    public var Kings:Array = new Array();
    
    //fix bug 1 protobuf-actionscript3
    //dummy var using AliveChessLibrary.Commands.BigMapCommand. necessary to avoid following exception
    //ReferenceError: Error #1065: Variable NetworkInfo is not defined.
    //at global/flash.utils::getDefinitionByName()
    //at com.google.protobuf::Message/readFromCodedStream()
    private var KingsDummy:AliveChessLibrary.Commands.BigMapCommand.King = null;
    
  
  }
}