// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class GetUnityMapRequest extends Message {
    public function GetUnityMapRequest() {
      registerField("name","",Descriptor.STRING,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional string name = 1;
    public var name:String = "";
    
  
  }
}