// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class King extends Message {
    public function King() {
      registerField("KingId","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
      registerField("X","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,2);
      registerField("Y","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,3);
      registerField("KingName","",Descriptor.STRING,Descriptor.LABEL_OPTIONAL,4);
      registerField("KingExperience","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,5);
      registerField("KingMilitaryRank","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,6);
    }
    // optional int32 _kingId = 1;
    public var KingId:int = 0;
    
    // optional int32 _x = 2;
    public var X:int = 0;
    
    // optional int32 _y = 3;
    public var Y:int = 0;
    
    // optional string _kingName = 4;
    public var KingName:String = "";
    
    // optional int32 _kingExperience = 5;
    public var KingExperience:int = 0;
    
    // optional int32 _kingMilitaryRank = 6;
    public var KingMilitaryRank:int = 0;
    
  
  }
}