// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class MoveKingRequest extends Message {
    public function MoveKingRequest() {
      registerField("x","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
      registerField("y","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,2);
    }
    // optional int32 x = 1;
    public var x:int = 0;
    
    // optional int32 y = 2;
    public var y:int = 0;
    
  
  }
}