// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.BigMapCommand {

  public final class PointTypes {
  
    public static var None:Number = 0;
    public static var King:Number = 1;
    public static var Castle:Number = 2;
    public static var Mine:Number = 3;
    public static var Resource:Number = 4;
    public static var SingleObject:Number = 5;
    public static var MultyObject:Number = 6;
    public static var Landscape:Number = 7;
  
  }
}