// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class CrazyMessage extends Message {
    public function CrazyMessage() {
      registerField("message","",Descriptor.STRING,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional string message = 1;
    public var message:String = "";
    
  
  }
}