// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.CastleCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class BuildingInCastleRequest extends Message {
    public function BuildingInCastleRequest() {
      registerField("number","",Descriptor.ENUM,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional .AliveChessLibrary.Commands.CastleCommand.InnerBuildingType number = 1;
    public var number:Number = -1; //No default value for now...
    
  
  }
}