// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.CastleCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  import InnerBuilding;
  public final class BuildingInCastleResponse extends Message {
    public function BuildingInCastleResponse() {
      registerField("buildingsList","InnerBuilding",Descriptor.MESSAGE,Descriptor.LABEL_REPEATED,1);
    }
    // repeated .AliveChessLibrary.Commands.CastleCommand.InnerBuilding buildings_list = 1;
    public var buildingsList:Array = new Array();
    
    //fix bug 1 protobuf-actionscript3
    //dummy var using AliveChessLibrary.Commands.CastleCommand. necessary to avoid following exception
    //ReferenceError: Error #1065: Variable NetworkInfo is not defined.
    //at global/flash.utils::getDefinitionByName()
    //at com.google.protobuf::Message/readFromCodedStream()
    private var buildingsListDummy:AliveChessLibrary.Commands.CastleCommand.InnerBuilding = null;
    
  
  }
}