// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.CastleCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  import Unit;
  public final class GetArmyCastleToKingResponse extends Message {
    public function GetArmyCastleToKingResponse() {
      registerField("arm","Unit",Descriptor.MESSAGE,Descriptor.LABEL_REPEATED,1);
    }
    // repeated .AliveChessLibrary.Commands.CastleCommand.Unit arm = 1;
    public var arm:Array = new Array();
    
    //fix bug 1 protobuf-actionscript3
    //dummy var using AliveChessLibrary.Commands.CastleCommand. necessary to avoid following exception
    //ReferenceError: Error #1065: Variable NetworkInfo is not defined.
    //at global/flash.utils::getDefinitionByName()
    //at com.google.protobuf::Message/readFromCodedStream()
    private var armDummy:AliveChessLibrary.Commands.CastleCommand.Unit = null;
    
  
  }
}