// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.CastleCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  import ResBuild;
  public final class GetRecBuildingsResponse extends Message {
    public function GetRecBuildingsResponse() {
      registerField("resBuild","ResBuild",Descriptor.MESSAGE,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional .AliveChessLibrary.Commands.CastleCommand.ResBuild resBuild = 1;
    public var resBuild:AliveChessLibrary.Commands.CastleCommand.ResBuild = null;
    
  
  }
}