// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.CastleCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class GetRecBuildingsRequest extends Message {
    public function GetRecBuildingsRequest() {
      registerField("type","",Descriptor.ENUM,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional .AliveChessLibrary.Commands.CastleCommand.InnerBuildingType type = 1;
    public var type:Number = -1; //No default value for now...
    
  
  }
}