// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.CastleCommand {

  public final class InnerBuildingType {
  
    public static var Voencomat:Number = 0;
    public static var Stable:Number = 1;
    public static var SchoolOfficers:Number = 2;
    public static var VVU:Number = 3;
    public static var GeneralStaff:Number = 4;
  
  }
}