// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.CastleCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class InnerBuilding extends Message {
    public function InnerBuilding() {
      registerField("InnerBuildingId","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,1);
      registerField("ResourceCountToBuild","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,2);
      registerField("ResourceCountToProduceUnit","",Descriptor.INT32,Descriptor.LABEL_OPTIONAL,3);
      registerField("ResourceTypeToBuild","",Descriptor.ENUM,Descriptor.LABEL_OPTIONAL,4);
      registerField("ResourceTypeToProduceUnit","",Descriptor.ENUM,Descriptor.LABEL_OPTIONAL,5);
      registerField("InnerBuildingType","",Descriptor.ENUM,Descriptor.LABEL_OPTIONAL,6);
      registerField("Name","",Descriptor.STRING,Descriptor.LABEL_OPTIONAL,7);
    }
    // optional int32 _innerBuildingId = 1;
    public var InnerBuildingId:int = 0;
    
    // optional int32 _resourceCountToBuild = 2;
    public var ResourceCountToBuild:int = 0;
    
    // optional int32 _resourceCountToProduceUnit = 3;
    public var ResourceCountToProduceUnit:int = 0;
    
    // optional .AliveChessLibrary.Commands.CastleCommand.ResourceTypes _resourceTypeToBuild = 4;
    public var ResourceTypeToBuild:Number = -1; //No default value for now...
    
    // optional .AliveChessLibrary.Commands.CastleCommand.ResourceTypes _resourceTypeToProduceUnit = 5;
    public var ResourceTypeToProduceUnit:Number = -1; //No default value for now...
    
    // optional .AliveChessLibrary.Commands.CastleCommand.InnerBuildingType _innerBuildingType = 6;
    public var InnerBuildingType:Number = -1; //No default value for now...
    
    // optional string _name = 7;
    public var Name:String = "";
    
  
  }
}