// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.CastleCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class ShowArmyKingRequest extends Message {
    public function ShowArmyKingRequest() {
    }
  
  }
}