// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.CastleCommand {

  public final class UnitType {
  
    public static var Knight:Number = 0;
    public static var Queen:Number = 1;
    public static var Rook:Number = 2;
    public static var Bishop:Number = 3;
    public static var Pawn:Number = 10;
  
  }
}