// Generated by the protocol buffer compiler.  DO NOT EDIT!

package AliveChessLibrary.Commands.ErrorCommand {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class ErrorMessage extends Message {
    public function ErrorMessage() {
      registerField("Message","",Descriptor.STRING,Descriptor.LABEL_OPTIONAL,1);
    }
    // optional string _message = 1;
    public var Message:String = "";
    
  
  }
}